leonardo_module_art_folio/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from feincms.translations import (TranslatedObjectManager,
                                  TranslatedObjectMixin, Translation)
from django.utils import timezone
from django.core.urlresolvers import reverse

CHOICES_IMAGE_STATUS = (
    ('available', _('Available')),
    ('sold_out', _('Not for sale / Sold out')),
)

CHOICES_PRODUCT_STATUS = (
    ('available', _('Available')),
    ('sold_out', _('Sold out')),
)

CHOICES_ORDER_STATUS = (
    ('sold_out', _('Reserve')),
    ('copy', _('Order copy')),
)

class Project(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    @property
    def primary_image(self):
        return self.images.filter(featured=True).first()

    @property
    def get_absolute_url(self):
        from leonardo.module.web.widget.application.reverse import app_reverse
        return app_reverse(
            'art_detail_project',
            'leonardo_module_art_folio.apps.projects',
            kwargs={
                'slug': self.translation.slug})

    class Meta:
        ordering = ['ordering']
        verbose_name = _("Project")
        verbose_name_plural = _("Projects")


class ProjectTranslation(Translation(Project)):

    """
    Translated project.
    """

    name = models.CharField(
        max_length=255, verbose_name=_("Name"), default='')
    slug = models.SlugField(_("Slug"), unique=True)
    description = models.TextField(verbose_name=_("Description"), blank=True, null=True, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name

class ImageCategory(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    class Meta:
        ordering = ["ordering"]
        verbose_name = _("Image category")
        verbose_name_plural = _("Image categories")


class ImageCategoryTranslation(Translation(ImageCategory)):

    """
    Translated Project Image Category.
    """

    name = models.CharField(
        verbose_name=_("Name"), max_length=255, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name


class ImageTheme(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    class Meta:
        ordering = ["ordering"]
        verbose_name = _("Image theme")
        verbose_name_plural = _("Image themes")


class ImageThemeTranslation(Translation(ImageTheme)):

    """
    Translated Project Image Category.
    """

    name = models.CharField(
        verbose_name=_("Name"), max_length=255, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name


class ImageColors(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    class Meta:
        ordering = ["ordering"]
        verbose_name = _("Image color")
        verbose_name_plural = _("Image colors")


class ImageColorsTranslation(Translation(ImageColors)):

    """
    Translated Project Image Category.
    """

    name = models.CharField(
        verbose_name=_("Name"), max_length=255, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name


class ImageFormat(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    class Meta:
        ordering = ["ordering"]
        verbose_name = _("Image format")
        verbose_name_plural = _("Image formats")


class ImageFormatTranslation(Translation(ImageFormat)):

    """
    Translated Project Image Category.
    """

    name = models.CharField(
        verbose_name=_("Name (eg. 120x120cm)"), max_length=255, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name


class ImageTechnique(models.Model, TranslatedObjectMixin):
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)

    objects = TranslatedObjectManager()

    def __unicode__(self):
        trans = None

        # This might be provided using a .extra() clause to avoid hundreds of
        # extra queries:
        if hasattr(self, "preferred_translation"):
            trans = getattr(self, "preferred_translation", u"")
        else:
            try:
                trans = unicode(self.translation)
            except models.ObjectDoesNotExist:
                pass
            except AttributeError:
                pass

        if trans:
            return trans
        else:
            return str(self.ordering)

    class Meta:
        ordering = ["ordering"]
        verbose_name = _("Image technique")
        verbose_name_plural = _("Image techniques")


class ImageTechniqueTranslation(Translation(ImageTechnique)):

    """
    Translated Project Image Category.
    """

    name = models.CharField(
        verbose_name=_("Name (eg. 120x120cm)"), max_length=255, default='')

    class Meta:
        verbose_name = _("Translation")
        verbose_name_plural = _("Translations")

    def __unicode__(self):
        return self.name


class ProjectImage(models.Model, TranslatedObjectMixin):
    project = models.ForeignKey(
        Project, related_name="images", verbose_name=_("Project"))
    image = models.ImageField(
        verbose_name=_("Project Image"), upload_to="project_images/")
    # main attributes
    categories = models.ManyToManyField(
        ImageCategory, verbose_name=_("Categories"), blank=True, null=True)
    theme = models.ManyToManyField(
        ImageTheme, verbose_name=_("Theme"), blank=True, null=True)
    colors = models.ManyToManyField(
        ImageColors, verbose_name=_("Colors"), blank=True, null=True)
    image_format = models.ManyToManyField(
        ImageFormat, verbose_name=_("Format"), blank=True, null=True)
    technique = models.ManyToManyField(
        ImageTechnique, verbose_name=_("Technique"), blank=True, null=True)
    # others
    ordering = models.PositiveIntegerField(
        verbose_name=_("Ordering"), default=0)
    featured = models.BooleanField(
        verbose_name=_("Featured Image"), default=False)
    # status
    status = models.CharField(
        verbose_name=("Status"), default=CHOICES_IMAGE_STATUS[0][0], choices=CHOICES_IMAGE_STATUS, max_length=255)

    pub_date = models.DateTimeField(
        _('Published on'),

leonardo_module_art_folio/templates/leonardo_module_art_folio/_orderimage_form.html
{% extends "leonardo/common/_modal.html" %}

{% load thumbnail leonardo_tags leonardo_page_tags %}
{% load i18n staticfiles crispy_forms_tags %}

{% block form_id %}artfolio_form{% endblock %}
{% block form_action %}
{% if copy_view %}
{% app_reverse 'picture_copy' 'leonardo_module_art_folio.apps.projects' pk=picture.id %}
{% else %}
{% app_reverse 'picture_order' 'leonardo_module_art_folio.apps.projects' pk=picture.id %}
{% endif %}
{% endblock %}

{% block modal-body %}
<style type="text/css">
a.full-screen {
    display: none;
}
a.close {
    padding-top: 8px;
}
textarea {
    height: 105px!important;
}
.pretty {
    display: block!important;
    margin-top: 9px!important;
    margin-bottom: 18px!important;
}
</style>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pretty-checkbox@3.0/dist/pretty-checkbox.min.css">
<h4>Název obrazu: <b>{{ picture.translation.name }}</b></h4>
<div class="row">
    <div class="col-md-6 padding-none">
    {% thumbnail picture.image "x350" format="PNG" as image %}
    <img style="width: 250px" class="order-project-image" src="{{ image.url }}" />
    {% endthumbnail %}
    </div>
    <div class="col-md-6 padding-none">
        <p>{% trans "Format" %}: {% for format in picture.image_format.all %}{{ format.translation.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
        {% if picture.status == 'copy' %}
        <p class='status available'>{% trans 'Available' %}</p>
        {% else %}
        <p class="status {{ picture.status }}">{{ picture.get_status_display }}</p>
        {% endif %}
    </div>
</div>
{{ block.super }}
<script type="text/javascript">
$(function(){
    $("#artfolio_form .radio").map(function(){
        $(this).removeClass("radio").addClass("pretty p-default p-round p-smooth");
        $(this).find("input").appendTo($(this));
        $(this).append("<div class='state p-primary'></div>");
        $(this).find("label").appendTo($(this).find(".state"));
    });
    function setButtonSubmitText() {
        if ($("input[value=copy]").is(":checked")) {
            $(".btn-submit-footer-modal").attr("value", "{% trans 'Order copy' %}");
            $("#artfolio_form").attr("action", "{% app_reverse 'picture_copy' 'leonardo_module_art_folio.apps.projects' pk=picture.id %}");
        }
        if ($("input[value=sold_out]").is(":checked")) {
            $(".btn-submit-footer-modal").attr("value", "{% trans 'Reserve' %}");
            $("#artfolio_form").attr("action", "{% app_reverse 'picture_order' 'leonardo_module_art_folio.apps.projects' pk=picture.id %}");
        }
    };
    $("input[type=radio]").click(function(){
        setButtonSubmitText();
    });
    {% if picture.status == 'sold_out' %}
    $("input[value=sold_out]").parent().remove();
    {% endif %}
    {% if copy_view %}
    $("input[value=copy]").trigger("click");
    setButtonSubmitText();
    {% else %}
    $("input[value=sold_out]").trigger("click");
    setButtonSubmitText();
    {% endif %}
});
</script>
{% endblock %}

{% block modal-footer %}
<input class="btn btn-default center-block btn-submit-footer-modal" type="submit" value="{{ submit_label }}" />
{% endblock %}

leonardo_module_art_folio/templates/leonardo_module_art_folio/orderimage_email.html
<h2>{{ order_title }} - {{ order.name }} - {% now "d.m. Y H:i" %}</h2>

<table style="border: 1px solid #e8e8e8;padding: 6px;width: 100%;border-collapse: collapse;">
    <tr style="background-color: #f3f3f3">
        <th style="text-align: left;padding: 8px;">Název obrazu:</th>
        <th style="text-align: left;padding: 8px;">
            {% if domain %}
            <a href="{{ domain }}/admin/leonardo_module_art_folio/projectimage/{{ order.picture.id }}/" target="_blank">{{ order.picture.translation.name }}</a>
            {% else %}
            {{ order.picture.translation.name }}
            {% endif %}
        </th>
    </tr>
    <tr style="background-color: #ffffff">
        <td style="text-align: left;padding: 8px">Jméno:</td>
        <td style="text-align: left;padding: 8px">{{ order.name }}</td>
    </tr>
    <tr style="background-color: #f3f3f3">
        <td style="text-align: left;padding: 8px">Telefon:</td>
        <td style="text-align: left;padding: 8px">{% if order.telephone %}{{ order.telephone }}{% else %}-- nevyplněno --{% endif %}</td>
    </tr>
    <tr style="background-color: #ffffff">
        <td style="text-align: left;padding: 8px">Email:</td>
        <td style="text-align: left;padding: 8px">{{ order.email }}</td>
    </tr>
    <tr style="background-color: #f3f3f3">
        <td style="text-align: left;padding: 8px">Poznámka:</td>
        <td style="text-align: left;padding: 8px">{% if order.note %}{{ order.note }}{% else %}-- nevyplněno --{% endif %}</td>
    </tr>
    <tr style="background-color: #ffffff">
        <td style="text-align: left;padding: 8px">Stav:</td>
        <th style="text-align: left;padding: 8px">{{ order.get_status_display }}</th>
    </tr>
</table>

leonardo_module_art_folio/templates/leonardo_module_art_folio/orderimage_form.html
{% extends "leonardo/common/modal.html" %}
{% load i18n staticfiles %}

{% block title %}{% trans "Order" %}{% endblock %}

{% block page_header %}
{% include "horizon/common/_page_header.html" with title=_("Order") %}
{% endblock %}

{% block body_main %}
{% include "leonardo_module_art_folio/_orderimage_form.html" %}
{% endblock %}

leonardo_module_art_folio/templates/leonardo_module_art_folio/project_detail.html
{% extends widget.get_base_template %}

{% load i18n %}
{% load leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}
{% include "leonardo_module_art_folio/fullscreen_pictures.html" with picture_list=object.images.all similar=projects search_view=False %}
{% endblock %}

leonardo_module_art_folio/templates/leonardo_module_art_folio/project_list.html
{% extends widget.get_base_template %}

{% load i18n leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}
<style>
.main-list {
  padding-top: 80px;
}
button.btn.btn-default {
    height: 34px;
}
</style>
<div class="container main-list">

  <div class="project-list">
    <div class="search-form">
    </div>
    <div class="container">
  {% for project in object_list %}
    <a href="{{ project.get_absolute_url }}">
      <div class="col-sm-4">
        <h3>{{ project.translation.name }}</h3>
        {% thumbnail project.primary_image.image "300x300" as thumb%}
        <img src="{{ thumb.url }}">
        {% endthumbnail %}
      </div>
    </a>
  {% endfor %}
    </div>
  </div>

</div>
{% endblock %}

leonardo_module_art_folio/templates/leonardo_module_art_folio/project_search.html
{% extends widget.get_base_template %}

{% load i18n %}
{% load leonardo_tags leonardo_page_tags thumbnail %}

{% block content %}
{% include "leonardo_module_art_folio/fullscreen_pictures.html" with picture_list=picture_list similar=picture_list search_view=True %}
{% endblock %}

leonardo_module_art_folio/templates/leonardo_module_art_folio/search_form.html
{% load i18n crispy_forms_tags leonardo_tags leonardo_page_tags thumbnail %}

<style type="text/css">
.glyphicon-ok:before {
    content: "\f00c";
    font-family: fontawesome;
}
</style>

<form id="searchform" action="{% app_reverse 'art_search' 'leonardo_module_art_folio.apps.projects' %}" method="get" accept-charset="utf-8">
  <div class="input-group">
    <select class="selectpicker" data-width="170px" name="categories" multiple title="{% trans 'Choose category' %}">
      {% for category in all_categories %}
      <option value="{{ category.id }}" {% if category in selected_categories %}selected{% endif %}>{{ category.translation.name }}</option>
      {% endfor %}
    </select>
    <select class="selectpicker" data-width="170px" name="themes" multiple title="{% trans 'Choose theme' %}">
      {% for theme in all_themes %}
      <option value="{{ theme.id }}" {% if theme in selected_themes %}selected{% endif %}>{{ theme.translation.name }}</option>
      {% endfor %}
    </select>
    <select class="selectpicker" data-width="170px" name="colors" multiple title="{% trans 'Choose color' %}">
      {% for color in all_colors %}
      <option value="{{ color.id }}" {% if color in selected_colors %}selected{% endif %}>{{ color.translation.name }}</option>
      {% endfor %}
    </select>
    <select class="selectpicker" data-width="170px" name="formats" multiple title="{% trans 'Choose format' %}">
      {% for format in all_formats %}
      <option value="{{ format.id }}" {% if format in selected_formats %}selected{% endif %}>{{ format.translation.name }}</option>
      {% endfor %}
    </select>
    <select class="selectpicker" data-width="170px" name="status"  multiple title="{% trans 'Availability' %}">
      {% for status_key, status_name in all_statuses %}
      <option value="{{ status_key }}" {% if status_key in selected_status %}selected{% endif %}>{{ status_name }}</option>
      {% endfor %}
    </select>
    <input class="form-control" name="name" {% if get_name %}value="{{ get_name }}"{% endif %} type="text" placeholder="Hledaný výraz...">
    <span class="input-group-btn submit">
      <button class="btn btn-default" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
    </span>
  </div>
</form>

<script type="text/javascript">
$(function(){
  $(".selectpicker").selectpicker();
});
</script>